#!/usr/bin/env -S uv run python
"""Generate (and optionally run) a Renode function-level emulation scenario.

For firmware that is not cold-bootable (e.g. two-stage bootloader+app designs
like the FNIRSI scope — see notes/firmware-bringup-runbook.md), the way to
exercise a peripheral driver is to enter the function directly with a synthetic
register/memory context and trace its MMIO against the platform's instrumented
stubs. This generalizes the hand-written stock_v120_handshake.resc.

Usage:
    scripts/renode/emulate_function.py --target stock_v120 \\
        --entry 0x0802A774 --stop 0x0802AB28 \\
        --reg sp=0x20036F90 --reg r6=0x40003C08 --reg r4=0x40011000 \\
        --reg r5=0xE000E010 --reg ip=0xFFFFFC14 --reg lr=0xFFFFFC10 \\
        --mem 0x20002B1C=0x40 --mem 0x20002B20=0x40 \\
        --platform scripts/renode/at32f403a.repl --run

Without --run it only writes the .resc (and prints the path). With --run it
invokes Renode, parses the trace into mmio_events JSONL, and prints a summary.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
RENODE = os.environ.get(
    "RENODE", "/Applications/Renode.app/Contents/MacOS/renode"
)

# ARM register name -> index (AAPCS aliases included).
REG_IDX = {**{f"r{i}": i for i in range(13)},
           "sp": 13, "lr": 14, "pc": 15,
           "ip": 12, "fp": 11, "sb": 9, "sl": 10}


def _coerce_int(v) -> int:
    return v if isinstance(v, int) else int(str(v), 0)


def load_target(name: str):
    import yaml

    cfg = yaml.safe_load((REPO / "config.yaml").read_text())
    t = cfg["targets"][name]
    return REPO / t["elf"], _coerce_int(t.get("base_addr", 0)), name


def parse_kv(items, label, key_int=False):
    out = []
    for it in items or []:
        if "=" not in it:
            sys.exit(f"error: --{label} expects key=value, got '{it}'")
        k, v = it.split("=", 1)
        key = int(k.strip(), 0) if key_int else k.strip()
        out.append((key, int(v, 0)))
    return out


def reg_set_line(name: str, val: int) -> str:
    name = name.lower()
    if name not in REG_IDX:
        sys.exit(f"error: unknown register '{name}'")
    if name == "pc":
        return f"cpu PC 0x{val:08X}"
    if name == "sp":
        return f"cpu SP 0x{val:08X}"
    return f"cpu SetRegisterUnsafe {REG_IDX[name]} 0x{val:08X}"


def build_resc(target, binary, base, platform, entry, stop, regs, mems,
               duration, trace_path, log_path) -> str:
    lines = [
        f'# Auto-generated by emulate_function.py — function-level emulation of {target}',
        f'mach create "{target}_fn"',
        f"machine LoadPlatformDescription @{platform}",
        f"sysbus LoadBinary @{binary.relative_to(REPO)} 0x{base:08X}",
        "",
    ]
    for addr, val in mems:
        lines.append(f"sysbus WriteDoubleWord 0x{addr:08X} 0x{val:08X}")
    if mems:
        lines.append("")
    for name, val in regs:
        lines.append(reg_set_line(name, val))
    lines.append(f"cpu PC 0x{entry:08X}")
    lines += [
        "",
        f"logLevel -1 sysbus",
        f"logFile $CWD/{log_path} true",
        f'cpu CreateExecutionTracing "tracer" $CWD/{trace_path} PCAndOpcode',
        "tracer TrackMemoryAccesses",
        "",
    ]
    if stop is not None:
        lines.append(f'cpu AddHook 0x{stop:08X} "self.Pause()"')
    lines.append(f'emulation RunFor "{duration}"')
    lines.append("quit")
    return "\n".join(lines) + "\n"


def summarize(trace_path: Path, platform_map: str, scenario: str, out_path: Path):
    """Parse the trace into mmio_events JSONL and print a summary."""
    sys.path.insert(0, str(REPO / "scripts" / "renode"))
    import parse_trace as pt

    pmap = pt.PERIPHERAL_MAPS.get(platform_map, [])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    events = list(pt.parse_trace(trace_path, scenario, pmap))
    with out_path.open("w") as f:
        import json
        for e in events:
            f.write(json.dumps(e) + "\n")

    from collections import Counter
    by_periph = Counter((e["peripheral"] or "unmapped", e["direction"]) for e in events)
    disp = out_path
    try:
        disp = out_path.relative_to(REPO)
    except ValueError:
        pass
    print(f"\nMMIO events: {len(events)}  ->  {disp}")
    for (p, d), n in sorted(by_periph.items(), key=lambda x: -x[1]):
        print(f"  {p:<12} {d:<5} {n}")
    # Per-peripheral write-value sequence (the command stream for each device).
    by_writes = {}
    for e in events:
        if e["direction"] == "write":
            by_writes.setdefault(e["peripheral"] or "unmapped", []).append(e["value"])
    for p, vals in sorted(by_writes.items(), key=lambda x: -len(x[1])):
        seq = " ".join(f"{v:02X}" for v in vals[:48])
        more = " ..." if len(vals) > 48 else ""
        print(f"  writes[{p}]: {seq}{more}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--target", required=True)
    ap.add_argument("--entry", required=True, help="start PC (0x...)")
    ap.add_argument("--stop", help="hook-pause address (0x...); ends the run early")
    ap.add_argument("--reg", action="append", metavar="NAME=VAL",
                    help="register context, e.g. r6=0x40003C08 (repeatable)")
    ap.add_argument("--mem", action="append", metavar="ADDR=VAL",
                    help="pre-set RAM word, e.g. 0x20002B1C=0x40 (repeatable)")
    ap.add_argument("--platform", default="scripts/renode/at32f403a.repl")
    ap.add_argument("--platform-map", default="at32f403a",
                    help="parse_trace peripheral map name (default: at32f403a)")
    ap.add_argument("--duration", default="0:0:2", help='RunFor time (default 0:0:2)')
    ap.add_argument("--out", help="output .resc path (default build/<target>_fn.resc)")
    ap.add_argument("--run", action="store_true", help="invoke Renode and parse the trace")
    ap.add_argument("--timeout", type=int, default=240, help="Renode wall-clock timeout (s)")
    args = ap.parse_args()

    binary, base, target = load_target(args.target)
    entry = int(args.entry, 0)
    stop = int(args.stop, 0) if args.stop else None
    regs = parse_kv(args.reg, "reg")
    mems = parse_kv(args.mem, "mem", key_int=True)

    label = f"0x{entry:08X}"
    trace_path = f"build/{target}_fn_{entry:08X}_trace.log"
    log_path = f"build/{target}_fn_{entry:08X}.log"
    resc = build_resc(target, binary, base, args.platform, entry, stop,
                      regs, mems, args.duration, trace_path, log_path)

    out = Path(args.out) if args.out else REPO / "build" / f"{target}_fn.resc"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(resc)
    print(f"wrote {out.relative_to(REPO) if out.is_relative_to(REPO) else out}")

    if not args.run:
        print(f"(dry run — re-invoke with --run, or: {RENODE} --disable-xwt --console {out})")
        return 0

    if not Path(RENODE).exists():
        sys.exit(f"error: Renode not found at {RENODE} (set $RENODE)")
    for stale in (REPO / trace_path, REPO / log_path):
        stale.unlink(missing_ok=True)

    print(f"running Renode (entry {label}, timeout {args.timeout}s)...")
    tp = REPO / trace_path
    # Renode --console can hang on shutdown after `quit`, so don't wait on the
    # process to exit. The execution tracer streams to the trace file during
    # the run; once that file stops growing the capture is done — kill Renode
    # and proceed. A still-growing trace at the deadline means a genuine spin.
    # Tell the platform's FPGA-stub peripheral where to import fpga_protocol.py
    # from, independent of Renode's working directory.
    env = dict(os.environ, RIPCORD_RENODE_DIR=str(REPO / "scripts" / "renode"))
    proc = subprocess.Popen(
        [RENODE, "--disable-xwt", "--console", str(out)],
        cwd=str(REPO), env=env, stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    deadline = time.monotonic() + args.timeout
    last_size, stable, spun = -1, 0, False
    while True:
        if proc.poll() is not None:
            break                                   # exited on its own
        if time.monotonic() > deadline:
            spun = True
            break
        size = tp.stat().st_size if tp.exists() else 0
        if size > 0 and size == last_size:
            stable += 1
            if stable >= 3:                         # ~3s with no new trace
                break
        else:
            stable = 0
        last_size = size
        time.sleep(1)
    if proc.poll() is None:
        proc.terminate()
        try:
            proc.wait(5)
        except subprocess.TimeoutExpired:
            proc.kill()
    if spun:
        print(f"  trace still growing at {args.timeout}s — likely a real spin; inspect it")

    if not tp.exists() or tp.stat().st_size == 0:
        sys.exit("error: no trace produced (check build/*_fn_*.log for errors)")
    summarize(tp, args.platform_map, f"fn_{entry:08X}",
              REPO / "build" / target / f"mmio_events_fn_{entry:08X}.jsonl")
    return 0


if __name__ == "__main__":
    sys.exit(main())
